import openMenu from './modules/openMenu';
import openFreeVisitForm from './modules/openFreeVisitForm';
import openCallBackForm from './modules/OpenCallBackForm';
import openGift from './modules/gift';
import sendForm from './modules/sendForm';
import burger from './modules/burgerMenu';
import arrow from "./modules/upArrow";
import calc from "./modules/calc";
import openThanks from "./modules/openThanks";
import slider from "./modules/slider";
import sliderServices from "./modules/uslugiCarusel";
import sliderGallery from "./modules/gallerySlider";

openMenu();
openFreeVisitForm();
openCallBackForm();
openGift();
sendForm();
burger();
arrow();
calc();
openThanks();
slider();
sliderServices();
sliderGallery();